In [1]:
import numpy as np
import scipy as sp
import matplotlib
import matplotlib.pyplot as plt

In [2]:
from iminuit import Minuit
from iminuit.cost import LeastSquares

In [3]:
# ----- Update path to script folder -----
import os
path = os.path.dirname(os.path.abspath(''))
os.chdir(path)

# ----- Import home-made packages -----
from yukawa5d import *
from constants import const

In [4]:
param_array = np.concatenate((    
    generateRandomParameters(3), # yu
    generateRandomParameters(3)  # yd
    ))
data_x = np.array([param_array])

c_array = np.array((0, 1, 1, 1, 1, 0, 0, 0, 10))

res = predictCKMfromParams(data_x, c_array)
res

array([ 2.95683672,  1.1363231 ,  0.29593408,  8.7097965 ,  0.33244257,
        0.08056057,  0.95888037,  0.19943549,  0.78715752, -1.58922273])

In [5]:
data_y = np.array([
    [ const.Yukawa[ y ]["val"] for y in ["u", "c", "t", "d", "s", "b"] ] +
    [ const.CKM[ y ]["val"] for y in ["s12", "s13", "s23", "delta"] ] 
])

data_yerr = np.array([
    [ const.Yukawa[ y ]["sdev"] for y in ["u", "c", "t", "d", "s", "b"] ] +
    [ const.CKM[ y ]["sdev"] for y in ["s12", "s13", "s23", "delta"] ]
])

least_squares = LeastSquares(data_x, data_y, data_yerr, yukawa5d.predictCKMfromParams)

NameError: name 'yukawa5d' is not defined

In [36]:
m = None

In [37]:
m = Minuit(least_squares, (1., 0., 0., 0., 0., 0., 0., 0., 0.) )

In [38]:
m.limits = ([-5., 10])

In [39]:
m

┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │   1.00    │   0.01    │            │            │   -5    │   10    │       │
│ 1 │ x1   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 2 │ x2   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 3 │ x3   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 4 │ x4   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 5 │ x5   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 6 │ x6   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 7 │ x7   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
│ 8 │ x8   │    0.0    │    0.1    │            │            │   -5    │   10    │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [57]:
m.migrad()  # finds minimum of least_squares function
m.hesse()   # accurately computes uncertainties

┌──────────────────────────────────┬──────────────────────────────────────┐
│ FCN = 4.834e+04                  │             Nfcn = 17376             │
│ EDM = 1.21 (Goal: 0.0002)        │                                      │
├───────────────┬──────────────────┼──────────────────────────────────────┤
│ Valid Minimum │ Valid Parameters │        No Parameters at limit        │
├───────────────┴──────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           Below call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │APPROXIMATE│NOT pos. def.│   FORCED   │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │ -1.795153 │ 0.000004  │            │            │   -5    │   10    │       │
│ 1 │ x1   │ -1.868082 │ 0.000006  │            │            │   -5    │   10    │       │
│ 2 │ x2   │-1.5893122 │ 0.0000009 │            │            │   -5    │   10    │       │
│ 3 │ x3   │ -4.98935  │  0.00024  │            │            │   -5    │   10    │       │
│ 4 │ x4   │  -3.049   │   0.022   │            │            │   -5    │   10    │       │
│ 5 │ x5   │ -4.63713  │  0.00024  │            │            │   -5    │   10    │       │
│ 6 │ x6   │  -4.533   │   0.022   │            │            │   -5    │   10    │       │
│ 7 │ x7   │-2.0369807 │ 0.0000005 │            │            │   -5    │   10    │       │
│ 8 │ x8   │-1.9582088 │ 0.0000029 │            │            │   -5    │   10    │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬───────────────────────────────────────────────────────────────────────────────────────────┐
│    │        x0        x1        x2        x3        x4        x5        x6        x7        x8 │
├────┼───────────────────────────────────────────────────────────────────────────────────────────┤
│ x0 │  1.54e-11  1.49e-11 -1.97e-12 -8.25e-11 -2.52e-08  8.57e-11  9.07e-09 -9.01e-13 -1.11e-11 │
│ x1 │  1.49e-11  3.72e-11 -2.14e-12 -1.14e-10 -2.91e-08  1.19e-10  1.22e-08 -9.39e-13 -1.35e-11 │
│ x2 │ -1.97e-12 -2.14e-12  8.09e-13  1.57e-11  4.07e-09 -1.64e-11 -1.69e-09  1.33e-13  1.75e-12 │
│ x3 │ -8.25e-11 -1.14e-10  1.57e-11  5.66e-08  2.62e-07  2.44e-08  2.17e-06  7.54e-12  6.61e-11 │
│ x4 │ -2.52e-08 -2.91e-08  4.07e-09  2.62e-07  0.000467 -2.52e-07 -2.82e-05   1.9e-09  2.19e-08 │
│ x5 │  8.57e-11  1.19e-10 -1.64e-11  2.44e-08 -2.52e-07  5.85e-08 -2.32e-06 -7.83e-12 -6.86e-11 │
│ x6 │  9.07e-09  1.22e-08 -1.69e-09  2.17e-06 -2.82e-05 -2.32e-06  0.000482 -8.06e-10 -7.34e-09 │
│ x7 │ -9.01e-13 -9.39e-13  1.33e-13  7.54e-12   1.9e-09 -7.83e-12 -8.06e-10   2.2e-13  7.99e-13 │
│ x8 │ -1.11e-11 -1.35e-11  1.75e-12  6.61e-11  2.19e-08 -6.86e-11 -7.34e-09  7.99e-13  8.66e-12 │
└────┴───────────────────────────────────────────────────────────────────────────────────────────┘

In [58]:
yukawa5d.predictCKMfromParams(data_x, np.array(m.values))

array([1.77716039e-05, 2.41437027e-07, 1.41198723e-07, 1.96138812e-04,
       1.62731326e-04, 4.74355906e-07, 2.27429941e-01, 3.06566699e-03,
       9.07700207e-02, 1.22694167e+00])

In [5]:
phase_array = np.concatenate(( generateRandomPhases(3), generateRandomPhases(3) ))
x_array = np.array([ phase_array ])
var_array = np.concatenate((0.01 + np.random.rand(18), np.array([0., 1., 1., 1., 1., 0., 0., 0., 2.]) ))

In [6]:
res2 = predictCKMfromParams2(phase_array, var_array)
res2

array([0.60075704, 0.3467387 , 0.02056   , 0.90100935, 0.13317078,
       0.03145344, 0.6461361 , 0.26098303, 0.97658416, 1.0419609 ])

In [7]:
res2 = predictCKMfromParams2(x_array, var_array)
res2

array([0.60075704, 0.3467387 , 0.02056   , 0.90100935, 0.13317078,
       0.03145344, 0.6461361 , 0.26098303, 0.97658416, 1.0419609 ])

In [118]:
data_y = np.array([
    [ const.Yukawa[ y ]["val"] for y in ["u", "c", "t", "d", "s", "b"] ] +
    [ const.CKM[ y ]["val"] for y in ["s12", "s13", "s23", "delta"] ] 
])

data_yerr = np.array([
    [ const.Yukawa[ y ]["sdev"] for y in ["u", "c", "t", "d", "s", "b"] ] +
    [ const.CKM[ y ]["sdev"] for y in ["s12", "s13", "s23", "delta"] ]
])

var_array = np.concatenate((0.01 + np.random.rand(18), np.array([1., 2., 3., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]) ))

least_squares = LeastSquares(x_array, data_y, data_yerr, predictCKMfromParams2)

In [119]:
m2 = None

m2 = Minuit(least_squares, var_array)

m2.limits = ([[0.01, 4.]] * 18 + [[-2., 5.]] * 9)

m2.migrad()  # finds minimum of least_squares function
m2.hesse()   # accurately computes uncertainties

┌──────────────────────────────────┬──────────────────────────────────────┐
│ FCN = 2.188e+05                  │             Nfcn = 7785              │
│ EDM = 3.68e+21 (Goal: 0.0002)    │                                      │
├───────────────┬──────────────────┼──────────────────────────────────────┤
│INVALID Minimum│ Valid Parameters │        No Parameters at limit        │
├───────────────┴──────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           ABOVE call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │   Hesse FAILED   │APPROXIMATE│NOT pos. def.│ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │ 1.4229e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 1 │ x1   │ 1.2168e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 2 │ x2   │ 5.6773e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 3 │ x3   │ 1.2035e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 4 │ x4   │ 1.1175e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 5 │ x5   │  2.8099   │  0.0000   │            │            │  0.01   │    4    │       │
│ 6 │ x6   │ 1.6988e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 7 │ x7   │ 2.0207e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 8 │ x8   │ 1.0022e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 9 │ x9   │ 1.6613e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 10│ x10  │ 1.2188e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 11│ x11  │ 8.0852e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 12│ x12  │ 1.4627e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 13│ x13  │ 2.7085e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 14│ x14  │ 1.0596e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 15│ x15  │ 6.1938e-2 │ 0.0000e-2 │            │            │  0.01   │    4    │       │
│ 16│ x16  │ 1.9717e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 17│ x17  │ 1.3313e-1 │ 0.0000e-1 │            │            │  0.01   │    4    │       │
│ 18│ x18  │  -1.4898  │  0.0000   │            │            │   -2    │    5    │       │
│ 19│ x19  │  -1.9647  │  0.0000   │            │            │   -2    │    5    │       │
│ 20│ x20  │  -1.3307  │  0.0000   │            │            │   -2    │    5    │       │
│ 21│ x21  │-3.6427e-1 │ 0.0000e-1 │            │            │   -2    │    5    │       │
│ 22│ x22  │-3.0836e-1 │ 0.0000e-1 │            │            │   -2    │    5    │       │
│ 23│ x23  │  -1.1369  │  0.0000   │            │            │   -2    │    5    │       │
│ 24│ x24  │  -1.913   │   0.000   │            │            │   -2    │    5    │       │
│ 25│ x25  │  -1.3623  │  0.0000   │            │            │   -2    │    5    │       │
│ 26│ x26  │-1.7723e-1 │ 0.0000e-1 │            │            │   -2    │    5    │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [54]:
predictCKMfromParams2(x_array, np.array(m2.values))

array([3.33924846e-06, 2.69759817e-08, 3.59301431e-09, 2.45158672e-05,
       2.54209216e-07, 2.49965057e-08, 2.26516808e-01, 3.61431291e-03,
       4.05116875e-02, 1.19600960e+00])

In [55]:
data_y

array([[3.29456e-06, 1.65737e-03, 4.97757e-01, 2.44146e-05, 4.86184e-04,
        2.37974e-02, 2.26500e-01, 3.61000e-03, 4.05300e-02, 1.19600e+00]])